name: CMake

on: [push]

#env:
#  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Apt update
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/debug_build
        cmake -E make_directory ${{github.workspace}}/build
        cmake -E make_directory ${{github.workspace}}/asan_build
        cmake -E make_directory ${{github.workspace}}/tsan_build

    - name: DebugBuild
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug
        cmake --build . -j 8
    - name: UnitTest
      working-directory: ${{github.workspace}}/build
      shell: bash
      timeout-minutes: 1
      run: ctest -C Release -R "^test" --verbose

    - name: ReleaseBuild
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
        cmake --build . -j 8
    - name: UnitTest
      working-directory: ${{github.workspace}}/build
      shell: bash
      timeout-minutes: 1
      run: ctest -C Release -R "^test" --verbose
    - name: StressTest
      working-directory: ${{github.workspace}}/build
      shell: bash
      timeout-minutes: 5
      run: ctest -C Release -R "^stress_test" --verbose

    - name: AsanBuild
      working-directory: ${{github.workspace}}/asan_build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=ASAN
        cmake --build . -j 8
    - name: UnitTest
      working-directory: ${{github.workspace}}/asan_build
      shell: bash
      timeout-minutes: 1
      run: ctest -C Release -R "^test" --verbose
    - name: StressTest
      working-directory: ${{github.workspace}}/asan_build
      shell: bash
      timeout-minutes: 1
      run: ctest -C Release -R "^stress_test" --verbose

    - name: TsanBuild
      working-directory: ${{github.workspace}}/tsan_build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=TSAN
        cmake --build . -j 8
    - name: UnitTest
      working-directory: ${{github.workspace}}/tsan_build
      shell: bash
      timeout-minutes: 1
      run: ctest -C Release -R "^test" --verbose
